# Site settings
title: Cut Digital Waste
email: support@kubeify.com
description: >
  Discover how to eliminate digital waste and reclaim your profits with our proven L.E.A.N-X™ framework. Book your free audit today!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cutdigitalwaste.com/" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
paginate: 1
# paginate_path: "/_posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

jekyll_admin:
  hidden_links:
    - datafiles

sass:
  sass_dir: _sass
  style: compressed

collections:
  podcasts:
    output: true
    permalink: /podcasts/:title/
